// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Cart__FormController from "./cart/form_controller"
application.register("cart--form", Cart__FormController)

import Cart__ItemController from "./cart/item_controller"
application.register("cart--item", Cart__ItemController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import Product__LikeController from "./product/like_controller"
application.register("product--like", Product__LikeController)

import QuantityController from "./quantity_controller"
application.register("quantity", QuantityController)
